quarkus.qdrant.devservices.collections.documents.vector-size=4
quarkus.qdrant.devservices.collections.documents.distance=Cosine
quarkus.qdrant.devservices.collections.products.vector-size=4
quarkus.qdrant.devservices.collections.products.distance=Cosine
